name: todolist
description: "A new Flutter project."
publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=3.2.5 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter  
  cupertino_icons: 1.0.2
  sqflite: 2.3.2
  path: 1.8.3
  provider: 6.1.1
  validatorless: 1.2.3
  intl: 0.18.1
  asyncstate: 2.1.0
  loading_animation_widget: 1.2.0+4
  top_snackbar_flutter: 3.1.0
  flutter_overlay_loader: 2.0.0
  date_picker_timeline: 1.2.5
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  flutter_native_splash: 2.3.10

flutter:
  uses-material-design: true
  
  assets:
    - assets/
